### ISSUE TITLE
missing graphql-codegen for react hooks

### ISSUE THREAD

**Issue by capaj** [karanpratapsingh/fullstack-starterkit#12]
The readme claims that types are important.
I agree with that and I think this repo doesn't do the type safety justice. It really needs to have https://graphql-code-generator.com/ set up. Please include it in here. Most people don't know how to set it up from scratch and only by using that you can get 100% fullstack typesafety.

If you don't know how to set it up, would you accept a PR with it?

**Comment by karanpratapsingh** [comment]
Thanks for trying this out, I'm not sure I understand correctly, this project is already using graphql codegen under `backend/packages/graphql`, check here https://github.com/karanpratapsingh/fullstack-starterkit/blob/master/backend/packages/graphql/codegen.yml , If you think it's missing an additional plugin. let's discuss 😄

**Comment by capaj** [comment]
@karanpratapsingh I meant for generating react hooks on the frontend. Not just for backend types.

**Comment by karanpratapsingh** [comment]
Hey feel free to add a pr
