### ISSUE TITLE
Example and usage

### ISSUE THREAD

**Issue by gaultierq** [karanpratapsingh/fullstack-starterkit#17]
Thanks for this starter it's really useful when you want to level up on graphql.
It would be quite useful to provide a small tutorial on how to add new models and use them in the client. There is quite a few scripts to run, generated files, and I think that a few lines in the REAMDME would flatten the learning curve quite a lot. 
For ex: I want to create a list of todos, and display it in the client somewhere.

**Comment by karanpratapsingh** [comment]
Thanks for opening the issue @gaultierq, can you provide some more description

Thanks
Karan

**Comment by gaultierq** [comment]
Hey @karanpratapsingh ! Don't know if you saw it but I edited my first comment :)

**Comment by karanpratapsingh** [comment]
apologies for the late reply, I've been bit busy past few weeks. I'm not sure about this, imo there is almost no learning curve to this boiler plate as it follows quite basic user->post example setup, adding an additional specific examples might not be of much use, tho I like your idea and would likely add examples in a separate repo
