### ISSUE TITLE
install workflow for production

### ISSUE THREAD

**Issue by gaultierq** [karanpratapsingh/fullstack-starterkit#18]
`NODE_ENV` set to 'production' will result in a failing `yarn` 
Indeed the `postinstall` steps depends on `devDependencies` which won't be available in production.
Changing `postinstall` step in `prepare` could be an option to consider.

**Comment by karanpratapsingh** [comment]
Hey @gaultierq I've fixed this, please take a look at PR #19, feel free to reopen the issue if it still persists
