### ISSUE TITLE
lerna to manage packages better

### ISSUE THREAD

**Issue by arslnb** [karanpratapsingh/fullstack-starterkit#20]
Consider using [Lerna](https://lerna.js.org/) to manage the packages. It comes with some neat features like hoisting, etc that you may find useful

**Comment by karanpratapsingh** [comment]
Thanks for opening the issue, yes lerna is great, however in this project only the `backend` is a yarn workspace and it's already hoisting packages quite nicely. I'm not sure how lerna might help in this small project. I would love some examples if you think lerna can create an impact in this project

**Comment by karanpratapsingh** [comment]
okay I am closing this as of now, feel free to reopen or submit a PR if you think lerna can help, thank your insights
