### ISSUE TITLE
Start backend and client under the same process?

### ISSUE THREAD

**Issue by miguelhrocha** [karanpratapsingh/fullstack-starterkit#24]
I was thinking that we can add a `devDependency` to concurrently and start both components at the same time. What do you think? I have a commit ready to be submitted to PR

**Comment by dorobila** [comment]
@miguelhrocha Submit the PR and see what happends.

**Comment by karanpratapsingh** [comment]
@miguelhrocha @dorobila sorry, I somehow forgot to reply to this thread. This sounds like a great idea, I also use `concurrently` package for this in another project. Tho I've noticed that many devs prefer to start their processes separately as well. So I left that choice to the developers
