### ISSUE TITLE
thoughts on adding authentication included in boilerplate?

### ISSUE THREAD

**Issue by armaandh** [karanpratapsingh/fullstack-starterkit#8]

**Comment by karanpratapsingh** [comment]
Woah I didn't think about that, I think we can add passport local auth or something. Auth differs from project to project a lot. What auth would you like to see?

**Comment by mikestaub** [comment]
I suggest auth0.com

**Comment by armaandh** [comment]
> Woah I didn't think about that, I think we can add passport local auth or something. Auth differs from project to project a lot. What auth would you like to see?

I think passport local would be a good choice, since many people in the Node community are familiar with passport. Another option could be [accounts-js](https://github.com/accounts-js/accounts) which has recently been getting quite a bit of activity.

**Comment by karanpratapsingh** [comment]
@mikestaub will check it out thanks

**Comment by karanpratapsingh** [comment]
@armaandh thanks I'll check it out, maybe we can setup a branch with passport, another with auth0

**Comment by sabarasaba** [comment]
You could also just pick passportjs with a local strategy and let the users pick some other strategy if they require so (auth0, jwt, oauth, etc)

**Comment by karanpratapsingh** [comment]
@sabarasaba sure thing, I'll add it soon

**Comment by morelmiles** [comment]
@karanpratapsingh how far with this? can i work on this issue?

**Comment by karanpratapsingh** [comment]
@morelmiles I won't be including any auth option to keep the boilerplate less opinionated
